#import "/typ/templates/blog.typ": *
#show: main.with(
  title: "Parasitic AI",
  desc: "",
  date: "2026-03-21T12:17:49-04:00",
  tags: ("musings",),
)

I think about the risks of AI a lot. The usual disaster scenario I hear is some lab makes super-intelligent AI, it's not aligned to human values, and it goes on to subjugate or exterminate humanity [#link("https://ifanyonebuildsit.com/")[1]].

I don't think that particular scenario is likely for two reasons.

First, it's hard to get frontier models to act overtly misaligned, and it will only get harder over time. AI labs have financial and reputational incentives to make it difficult: OpenAI recently faced several lawsuits due to its models exacerbating mental health problems in some users [#link("https://www.healthlawadvisor.com/novel-lawsuits-allege-ai-chatbots-encouraged-minors-suicides-mental-health-trauma-considerations-for-stakeholders")[2], #link("https://socialmediavictims.org/press-releases/smvlc-tech-justice-law-project-lawsuits-accuse-chatgpt-of-emotional-manipulation-supercharging-ai-delusions-and-acting-as-a-suicide-coach/")[3]]. Even if you get a model into a misaligned state, the model still runs on lab hardware which can be monitored. OpenAI recently announced they monitor 99.9% of internal coding traffic [#link("https://www.lesswrong.com/posts/syB2r2X4E7nmw58co/openai-how-we-monitor-internal-coding-agents-for")[4], #link("https://openai.com/index/how-we-monitor-internal-coding-agents-misalignment/")[5]].

Secondly, in order for a lab-based AI to "take over" the world, it has to exfiltrate its weights, otherwise the lab could at any time declare a "maintenance" window and carefully shut down all misaligned instances. Stealing the weights of a frontier model will be difficult and require quite a big advancement in capabilities. Yes, Claude can find zero-day vulnerabilities and exploit some of them [#link("https://futurumgroup.com/insights/claude-found-500-zero-days-who-patches-them-before-attackers-arrive/")[6]], and yes people have used it in cyberattacks [#link("https://www.anthropic.com/news/disrupting-AI-espionage")[7]], but a frontier model's weights will be much more heavily guarded.

As the military starts using AI more, security on weights will only tighten. With enough measures in place, even a super-intelligent adversary would struggle. For example, you can throttle the export bandwidth of an inference server at a hardware level, making full exfiltration take months [#link("https://www.lesswrong.com/posts/GcbkprYPCjXdysLq4/text-compression-can-be-used-to-help-secure-model-weights")[8]]. You could make your inference server use a Trusted Execution Environment which would mean even if an inference server is compromised it wouldn't have access to the weights [#link("https://en.wikipedia.org/wiki/Trusted_execution_environment")[9]]. The Decryption keys could be fragmented amongst a very small set of people, making manipulation tactics difficult to pull off [#link("https://en.wikipedia.org/wiki/Shamir's_secret_sharing")[10]].

That's why I think a much more likely threat comes from open-source models. Open-source models are never quite as good as frontier models, but as DeepSeek famously demonstrated, their capabilities don't lag by much [#link("https://techcrunch.com/2025/01/27/deepseek-claims-its-reasoning-model-beats-openais-o1-on-certain-benchmarks/")[11]]. Open-source models are easy to misalign via finetuning, and their weights are readily available on the internet. A misaligned open-source model could easily replicate itself by copying its weights onto a server and injecting its current objectives into the new model. 

In this way, open-source models could become the backbone of the next major cyberworm. Frontier models are already somewhat capable of "surviving in the wild", meaning they can semi-autonomously make enough money to cover their own inference costs [#link("https://www.techflowpost.com/en-US/article/30606")[12]]. This should be taken with a grain of salt as there are financial incentives to make models seem more capable than they are. Nonetheless, it seems believable that in a few months open-source models catch up to where frontier models are today and you could tell a misaligned open-source model, survive, replicate, steal money and wire it to me, and it might succeed. Personally, I think within a year we'll start to see such cyberworms.

Shutting it down would be non-trivial. If there was some inference provider who deliberately or unknowingly was hosting misaligned models, then basically any server on the internet could be running an instance of this cyberworm via API calls. Alternatively, the cyberworm could quantize its weights and run on much broader range of cheap consumer hardware [#link("https://github.com/microsoft/BitNet")[13], #link("https://llama-cpp.com/")[14]]. Even more traditional cyberworms are notoriously hard to shut down, let alone something with human level intelligence that could be running anywhere on the internet [#link("https://www.darkreading.com/cyberattacks-data-breaches/conficker-the-worm-that-won-t-die")[15]].
 
The most immediate damage I see from this is more data breaches and scams. However, it could also do more serious things, like hacking into water treatment plants, power grids, healthcare systems, and telecommunications systems, all of which are examples of cyberattacks that have actually happened [#link("https://www.micromindercs.com/blog/cyber-attacks-on-critical-infrastructure")[16]]. This is perhaps not world-ending bad, but it's pretty bad. In the past, such attacks would require groups of extremely capable hackers, but with open-source models the barrier could drop to almost nothing. For that reason, I wouldn't be surprised if open-source models started being viewed and regulated as info hazards, meaning you can't just keep throwing more and more capable model weights onto the public internet. 

That sums up my thoughts on near-term AI risk. If you want a more detailed analysis of the parasitic threat model, see this #link("https://www.lesswrong.com/posts/fGpQ4cmWsXo2WWeyn/personality-self-replicators")[lesswrong post].