#import "/typ/templates/blog.typ": *
#show: main.with(
  title: "TWOTM Theories (Spoilers)",
  desc: "",
  date: "2025-09-27T15:08:31-04:00",
  tags: ("thoughts", "books"),
)

1. Emissa is not a “traitor”. She expressed clearly to Vin before the Iudicium that the outcome of the competition mattered to her, and that they should stay together regardless. Hence, her stating that she needs to win isn’t treasonous, I’m sure she had a ton of pressure to win as well. As for the stabbing, she only did that after noticing his injury. I think the blood-taint that Veridus mentioned is probably why. It did feel cold, she stabbed him without a word of explanation of comfort, but it seems plausible this was how she was trained to react. She did cry, so I believe she truly loved him and felt it was necessary.
2. That said, Emissa is hiding things. She was obviously trying to get to know him from the very start. Unlike Callidus and Eidhn who confessed very revealing secrets to Vis, she never did, and it’s not because she’s innocent. She knows about blood-taints, she was able to use will despite all of the security measures, she had an obsidian knife (obsidian seems to have some religious significance and all the husks are stabbed with it). She also knew Indol’s deepest secret despite him not telling her. She knew the same dead language only Eidhn and Vis could speak…
3. Now that I think about it, Emissa seems too smart to have gotten caught in a riptide. If she can sneak will on to the island, she definitely could’ve used some to keep her calm and swim away. Perhaps she knows Diago’s past? Maybe she put the boat on his table? Reddit claims will doesn’t directly help with this but I’m not that sure. It would’ve made her stronger, possible strong enough to just swim against the riptide. It’s also very clear she’s no low-level will user given how easily she kills the Sextus and stabs Vis at the end. It seems impossible for her to have perfectly manipulated Indol into telling Vis she was going to be at a risky place where she might drown though. So… maybe not? After this point she might’ve been able to deduce he was Diago though.
4. The Alupi is honestly way too smart. It finds him immediately after he gets close to the temple (the forest is quite big). It tries to dissuade him from going in the temple. It kills everyone he thinks is an antagonist, *even when he’s not there*. For example, it killed the person attacking Callidus. It also hates being pet. It feels like it’s practically human.
5. The needle thing that Vis was given was for protection, as Relucia said. I think it just makes it clear to Mullior who in the crowd has Anguis ties. I think it also might have allowed him to get close to Mullior, as it seemed like Vis was going through some kind of barrier as he got close, and the needle kept increasing in heat.
6. Mullior is still alive. The guardsmen at the end said “Mullior is watching” and I don’t think it’s metaphorical considering that he had other-worldly powers and almost certainly through Synchronism himself. It also explains why he was willing to commit suicide, and why when Vis told him “be careful” he kind of disregarded it. Of course, he was literally planning on committing suicide, but I think he knows the Hierarchy will never be able to truly kill him considering his Synchronism.
7. Synchronism just means being alive in all three worlds at once. Makes a lot of sense. Synchronism is death also makes sense, as it seems like the temple was trying to kill Vis. It is clear that your clones are initially linked to you, and your bodies suffer equivalent damage and such. Hence, killing the version in Res could kill all your other versions, which is what Caeror is so worried about.  Hence, inscribing letters in Vis’s arms (R U …). However, it seems like once you leave that chamber the link becomes way more fragile (as Caeror also said) hence the letter N not appearing. 
8. Caeror and Lanista ran the maze together and they both made it to the cloning chamber. It feels unlikely either of them died in the maze on the way back, because it should be a lot easier.  Neither was captured or killed in the main chamber or all versions of both of them would be dead. Hence, the husks outside the maze probably got to them.
9. Lanista was captured and the husk conversion process was started (but I don’t think this truly kills you because the husks can kind of understand human language and Lanista would be dead otherwise). It seems husk conversion is a standard punishment for what the zombies do to you if you try to achieve Synchronism as stated by all of the Labyrinth guides. 
10. I’m not sure what happened to Caeror. My guess is his body was never found, hence Ulcisisor not knowing what really happened to him and wanting Vis to run through the Labyrinth. I initially thought this meant he could’ve died in the labyrinth on the way out but I think it’s unlikely, I also think that could kill his clones. Hence, maybe he made it out, made it past the husks but got so injured and infected that he died in Res. OR. Maybe both him and Lanista made it out of the maze, and Veridius was there. Lanista gets bitten or something early into the fight, and Caeror tells Veridius tells him to take her and run “sacrificing” himself to give her a chance to live. They do seem to have been in love. I think this makes the most sense. I doubt Veridius could’ve gone back and retrieved Lanista (it would’ve awakened all the corpses) nor would it line up with the timeline of Caeror’s death. I also doubt Veridius would kill Caeror even if he got bitten because then why haul Lanista back. 
11. That one dude “teleports” by moving into a different realm, walking around there, and then switching back realms. He says people are watching. Maybe because there’s some kind of disturbance if two copies of yourself exists in the same realm? Also, I imagine the pain he feels is because of the realm hopping.
12. Veridius is not evil but he’s some kind of hyper-utilitarian who believes preventing the next cataclysm is worth sacrificing students for. 
13. Who could’ve know about Vis’s ability to use the palace tunnels? Initially, this made me think one of his sisters must be alive but we seem to have good evidence that one was hanged and the other drowned at sea. Vis at least knew his sister had drowned, and pushed her back into the ocean. I guess it’s possible Vis’s former tutor lied about the hanging, he’s one of three people who actually saw it... it’s hard to prove anything about who was actually hanged. Still, given Vis’s tutor knew about the tunnels, there are probably other Suus informants who could’ve known as well, so maybe there’s not much we can deduce from here.
14. What was the secret the Hierarchy wanted from Suus? If it was related to these other worldly powers, then the knowledge clearly hasn’t been distilled to the rest of the Military. On the other hand, perhaps the head of the military, the guy responsible for the invasion of Suus, who openly is ok with the Anguis killing anyone, perhaps he is an Anguis plant and this is why the knowledge has not been spread. Perhaps this is why the Anguis seem to have gotten “bolder” recently, because they only recently captured Suus. My guess is that Suus has its own gate. Why else would Mullior imply his weapon has anything to do with Suus heritage? It also seems the Anguis are actively putting people through the gate. Like the guy with the scar we see at the end. He clearly is just getting used to his new powers as evidence by his discussion with Relucia. Getting onto the Academy without permission seems really hard (and possibly the gate is also more dangerous). This also makes it seem possible Vis’s father is alive in one of the other realms, as he definitely knew whatever secret Suus had.
15. Pretty obvious, but the blood on the cloak and the insane aggression of the safety team was because the Anguis had killed the safety team and put on their uniforms.
16. Another thing I’m wondering is, can Will users detect lies? It seems like if Vis really wanted to achieve his dream of getting rank 1, choosing an ideal position, and then not ceding will he would’ve been better off just saying he found Caeror’s huskified bodies in one of the chambers. Or he overhead Vedelius saying he killed him or something. From my perspective, seems to be blindly trusting Vis. Perhaps the reason he trusts him is because Lanista remembers more then she lets on, and she can partially verify that the things that Vis saw are real.
17. Ulcisisor knows far more then he lets on. Why does he have a private copy of the Labyrinth? First of all, the Labyrinth itself is a temple relic, and the instruction for how to obtain it would’ve been really hard to get. Second, you can make it all the way to class four before Labyrinth skills really start to become important. Class 4 is good enough if all you care about if finding out what happened to Caeror. There are simpler ways we could’ve chosen to create a “Labyrinth”-esque environment. It makes me thing he knew Vis would have to run the Labyrinth all along. The fact that he wasn’t direct about it makes me doubt this, because it doesn’t seem like such a bad thing to tell Vis. I think it’s probably because he was also just interested in everything else going on in the island, and he didn’t even know where the labyrinth was. Once he knew where it was, Vis was very clearly told he HAD to do it.
18. Cataclysm’s are a recurring phenomenon. This would explain why Veridius thinks one is impending. We know so little about pre-cataclysm life that it seems possible it could’ve actually happened many times. I wonder if reending is the same thing as a cataclysm.
19. Nobody? Has made it through the labyrinth (and survived) except Vis. Otherwise, how come Caeror doesn’t know Veridius is principalis? On the other hand, he does seem to expect Veridius to keep sending students through, which I almost implies Veridius knows Caeror is alive. But more likely, I think it implies Veridius has read through the ruins and knows the value of having someone achieve synchronicity.
20. Something I saw on Reddit: the Suus tunnels are connected to the Suus gate. Makes a lot of sense!
21. So long as the Husks have Obsidian in them they stay dead. Evidence is that Vis notices the husks basically only die if you stab their necks, normal injuries aren’t enough. So, either you do that, or… you carry around a specialized weapon which can kill them like Emissa. It also explains why the husks all have Obsidian in them, why the obsidian blades in the cloning chamber subdued the first wave of husks, and so on.
22. Callidus’s observation that there are way too few Sextus’s is actually very significant. I just interpreted it as good positions are harder to get then they tell you, but actually it means will in the system is “leaking”. There are unknown forces extracting will out of a large portion of people…
